# Generated by Django 3.2.13 on 2023-01-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20230125_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('SELLER', 'SELLER'), ('BUYER', 'BUYER'), ('ADMIN', 'ADMIN')], default='BUYER', max_length=20),
        ),
    ]
