# Generated by Django 3.2.13 on 2023-01-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('SELLER', 'SELLER'), ('BUYER', 'BUYER'), ('ADMIN', 'ADMIN')], max_length=20),
        ),
    ]
