# Generated by Django 3.2.13 on 2022-09-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220914_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='ùùmlùm', max_length=100),
            preserve_default=False,
        ),
    ]
