# Generated by Django 4.1 on 2022-09-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_key', models.CharField(max_length=100)),
            ],
        ),
    ]
