# Generated by Django 3.2.13 on 2023-01-21 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='order',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
    ]
