# Generated by Django 3.2.13 on 2022-09-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_hashsessions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HashSessions',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orders',
        ),
        migrations.AddField(
            model_name='order',
            name='count',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='product.Product'),
        ),
    ]
